### ISSUE TITLE
PyEnchant Win64

### ISSUE THREAD

**Issue by steamlord** [jrabbit/pyborg-1up#108]
I'm getting this error after `pip install pyborg`

> ImportError: The 'enchant' C library was not found. Please install it via your OS package manager, or use a pre-built binary wheel from PyPI.

**Comment by jrabbit** [comment]
I thought it avoided this unless you used the subtitles extra? How'd you
get here?

**Comment by jrabbit** [comment]
so it turns out I'm the pypi maintainer of the dep that's pulling this in... it can probably be removed. try installing without subtitle support.

**Comment by jrabbit** [comment]
plot twist #2 they removed that dep https://github.com/otsaloma/gaupol/blob/0e1c48f55bb3fd7aa75ff08e62d31fc30cb31f73/NEWS.md#2019-08-04-gaupol-17

**Comment by jrabbit** [comment]
it should work now

**Comment by jrabbit** [comment]
Any update? @steamlord

**Comment by jrabbit** [comment]
closing this for now, if there's a problem re-open or ping me
