### ISSUE TITLE
unable to run on ubuntu 21.04

### ISSUE THREAD

**Issue by MrChuw** [jrabbit/pyborg-1up#136]
![image](https://user-images.githubusercontent.com/14945734/125999778-e52cdc39-508f-4922-a5dc-0c51c66d1e26.png)

On my windows pc after solving some problems i was able to run, but on my linux it doesn't save the brain files. And also i can't run without http. (I probably did something wrong, but it costs nothing to ask for help :) )

**Comment by jrabbit** [comment]
oh that seems like a bug for sure. Can you tell me how you installed pyborg on linux specifically? I suspect pyborg is detecting systemd for some reason and trying to use an upgraded feature set that I missed in a refactor I think.

**Comment by MrChuw** [comment]
i used pip install pyborg, and all his files are the original ones except i change the ! of the commands for no one to use by accident

**Comment by jrabbit** [comment]
yeah i have an idea whats wrong, I expected systemd to exist as a library only when users enabled the package extra (e.g. pip install pyborg[systemd]). Is there any reason you wouldn't want systemd notify support even if you're not expecting it?

**Comment by MrChuw** [comment]
I have no problem with installing, but there was an error when I went to install so I decided not to try https://pastebin.com/6r0AwBt8

**Comment by MrChuw** [comment]
![image](https://user-images.githubusercontent.com/14945734/126009229-5b211f78-0105-4ce4-a051-8a923291e0f3.png)

I don't know if it says in the text but apparently systemd is already installed

**Comment by jrabbit** [comment]
Oh you already have the library and installed (pyborg) outside a virtualenv or https://pypa.github.io/pipx/. pyborg did something wrong based on being able to access that python library that ubuntu exposes at the system level.

**Comment by jrabbit** [comment]
I pushed some fixes to dev if you want to try it (other solution is to isolate pyborg's install in a virtualenv or have pipx do it for you)

**Comment by MrChuw** [comment]
it worked with pipx, I only have 2 requests, I would add in the configuration file an option to change the "!" of the commands to any other (currently I use type ¥ (alt 157) and one to make a backup in another folder if the bot or http stops (the backups being of different names)

**Comment by jrabbit** [comment]
the discord module takes a prefix in it's toml config as-is

~/.conf/pyborg/discord.toml
```toml
[discord]
prefix = "¥"
```

So you want to override where pyborg autosaves unnamed brains or something different entirely? (The distinction is important for if it's a config file thing or option in entrypoint/command line.)

**Comment by MrChuw** [comment]
when i was running on windows (it also couldn't overwrite the files)and  for some reason i closed the terminal and it saved in temp (i didn't know it was saved there), and then later when i found out it was saving there I had already lost 1 whole day, because it overwrites the old file, in this case it would be a way to save a backup regardless of whether it saves the brain or not
