### ISSUE TITLE
pyborg_experimental.py not found

### ISSUE THREAD

**Issue by Anonchan** [jrabbit/pyborg-1up#54]
Hello again! On build and install an error saying "pyborg_experimental.py" is not found. I found a workaround to copy it to "/usr/local/bin" ("/usr/local/bin/pyborg_experimental.py") works.

**Comment by jrabbit** [comment]
the script entrypoint is installed as `pyborg` do you have that?

**Comment by Anonchan** [comment]
yes, located in the same location

**Comment by Anonchan** [comment]
After reinstalling it is working now. I'm not sure what happened before. Thank you again.
