### ISSUE TITLE
Pyborg Discord not working. Using Python 3 (3.0.1) as described in the documentation.

### ISSUE THREAD

**Issue by KodaichiZero** [jrabbit/pyborg-1up#77]
![pyborg issue](https://user-images.githubusercontent.com/2176612/43031049-e7cc1814-8c67-11e8-9624-a90d51a56c29.png)

**Comment by KodaichiZero** [comment]
Seems to be a python version issue. Need a more specific version. I guessed that 3.0.1 might be okay but it's apparently not.

**Comment by jrabbit** [comment]
Hey thanks for looking into pyborg! Looks like you're using an old version
of 3. I'd recommend the latest versions of 3.6 or 3.7 I think we use type
annotations so we need 3.6+

**Comment by KodaichiZero** [comment]
Okay, I will try and let you know..

**Comment by KodaichiZero** [comment]
Python 3.7.0 is looking like the correct version but I am getting a different error:

Line 45 of pyborg.py, "import attr"
ModuleNotFoundError: No module named 'attr'

Think this is still a version problem, or maybe I'm missing a dependency of some kind?

**Comment by jrabbit** [comment]
That's a dependency how'd you install pyborg?

**Comment by jrabbit** [comment]
pls use pypi via pip.

**Comment by jrabbit** [comment]
Were you able to get pyborg running via `pip install`?

**Comment by jrabbit** [comment]
No signs of life.
