### ISSUE TITLE
unit services failed upon start

### ISSUE THREAD

**Issue by itz63c** [jrabbit/pyborg-1up#81]
stree@ubuntu:/lib/systemd$ systemctl start pyborg_http & systemctl start pyborg_discord
[1] 3897
A dependency job for pyborg_discord.service failed. See 'journalctl -xe' for details.
[1]+  Done                    systemctl start pyborg_http
stree@ubuntu:/lib/systemd$ journalctl -xe
-- Support: http://www.ubuntu.com/support
-- 
-- Unit pyborg_http.service has failed.
-- 
-- The result is RESULT.
Feb 27 14:30:25 ubuntu polkitd(authority=local)[786]: Operator of unix-session:2 successfully authent
Feb 27 14:30:25 ubuntu systemd[1]: pyborg_http.service: Start request repeated too quickly.
Feb 27 14:30:25 ubuntu systemd[1]: pyborg_http.service: Failed with result 'exit-code'.
Feb 27 14:30:25 ubuntu systemd[1]: Failed to start Pyborg multiplexing server.
-- Subject: Unit pyborg_http.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit pyborg_http.service has failed.
-- 
-- The result is RESULT.
Feb 27 14:30:25 ubuntu systemd[1]: Dependency failed for Pyborg Discord Client.
-- Subject: Unit pyborg_discord.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit pyborg_discord.service has failed.
-- 
-- The result is RESULT.
Feb 27 14:30:25 ubuntu systemd[1]: pyborg_discord.service: Job pyborg_discord.service/start failed wi
Feb 27 14:30:25 ubuntu polkitd(authority=local)[786]: Unregistered Authentication Agent for unix-proc
lines 1723-1748/1748 (END)

**Comment by jrabbit** [comment]
Hm Can you upload your .service files and tell me where you've installed the app at?

**Comment by itz63c** [comment]
https://gist.github.com/itz63c/d6e0767243b97f8cddb8a857ddfa5f5b
as for the install... to be quite fair it might not even be installed correctly, i just git cloned it and set it up through docker just chilling in /home/pyborg-1up because it kept failing to install via pip install pyborg

**Comment by jrabbit** [comment]
Ok the install is failing because it wants to build cryptography which needs openssl headers (openssl-dev likely)

Those unit files look right. Did you run `pipenv sync` to set up the venvs for the pyborg user?

**Comment by jrabbit** [comment]
Also the docker stuff is either/or with the systemd units

**Comment by itz63c** [comment]
i think ive determined all sorts of shit is fucked, i nuked it, you said the docker is either or with the systemd stuff? which do you recommend, sorry if i seem like a nuisance

**Comment by jrabbit** [comment]
The docker setup should be a little harder to break probably. Systemd is very finicky

**Comment by jrabbit** [comment]
Any further issues?
