### ISSUE TITLE
Unless I am blind

### ISSUE THREAD

**Issue by seitzbg** [jrabbit/pyborg-1up#82]
I've got the bot running on IRC, and the http server running as well.  I've trained it from file but it doesn't create a new brain or save anything.... help!

**Comment by jrabbit** [comment]
What's going on in the pyborg_httpd logs? There's not an irc command to save rn for some reason probably an oversight. /save should make it happen I think you post to that

**Comment by jrabbit** [comment]
https://github.com/jrabbit/pyborg-1up/blob/master/pyborg/pyborg/mod/mod_http.py#L39 yeah
