### ISSUE TITLE
different ways to call the bot on discord

### ISSUE THREAD

**Issue by itz63c** [jrabbit/pyborg-1up#89]
is there any sort of modification i can do to change how the bot is called while using pyborg for discord? i.e. instead of @'ing the bot i could just say a name i give it

**Comment by jrabbit** [comment]
I think it's checking for the bot's username which is in the (your) app settings (on discord's api website)? 
Yeah we use the discord.py discord.Client.user.mentioned_in() thing.

**Comment by jrabbit** [comment]
So you want it to respond to plaintext names too? Does it need to do this at runtime or per-server?

**Comment by itz63c** [comment]
Yeah, as plaintext. i.e `stree` instead of `@stree` like im doing now...

it could be done either way, i guess i'd prefer at the runtime

**Comment by itz63c** [comment]
did a bit of asking around in the discord.py group.. this can be achieved using 
`if self.user.name in message.content:`
or `if self.user.name.lower() in message.content.lower():` to make it case insensitive

**Comment by jrabbit** [comment]
Oh so not a configured name just what its nicknamed to? Much easier.
