### ISSUE TITLE
wont respond to owner commands

### ISSUE THREAD

**Issue by itz63c** [jrabbit/pyborg-1up#90]
i set owner=1 [here](https://github.com/jrabbit/pyborg-1up/blob/6194c777e46314c877c5e5964563ae8e25cd548f/pyborg/pyborg/pyborg.py#L458) but still cant get pyborg to respond to !owner or any other owner related commands

**Comment by jrabbit** [comment]
those aren't exposed to discord. They're in linein though.

**Comment by itz63c** [comment]
ah okay thanks

**Comment by itz63c** [comment]
can i easily expose them to discord?

**Comment by jrabbit** [comment]
Well there's no built in support for auth but you could write a commands.py command that uses the same http endpoint as linein for some functionality but it's really a security quagmire.

**Comment by itz63c** [comment]
how im suppose to access censor,unlearn,purge,replace through filein lol

**Comment by jrabbit** [comment]
linein is a repl
